### ISSUE TITLE
issue with windows 10 ,seems one of the table is missing

### ISSUE THREAD

**Issue by tsdeepak** [tuanavu/airflow-tutorial#14]
seems there is a missing table ...example_variables_config.

attached are the logs for docker-compose up 
[airflow_compoer.log](https://github.com/tuanavu/airflow-tutorial/files/2900142/airflow_compoer.log)

**Comment by tuanavu** [comment]
Hi @tsdeepak,

It is not a missing table. It is an Airflow variable that you need to import: https://github.com/tuanavu/airflow-tutorial/tree/master/examples/intro-example/dags/config

The guide to update the Airflow variable is included in the video tutorial.  Please follow the tutorial here: https://www.applydatascience.com/airflow/airflow-variables/

**Comment by tsdeepak** [comment]
Hi @tuanavu ,

thanks for the reply . but am not able to browse through to hosted airflow web-client. should i need to import the variable before docker-compose up ..?

thanks

**Comment by tuanavu** [comment]
Hi @tsdeepak,

When you first start `docker-compose up`. This is what you should see in the browser: http://localhost:8080/admin/ even with the missing variable.

![screen shot 2019-02-25 at 9 26 47 pm](https://user-images.githubusercontent.com/6547031/53389466-47ff8c00-3944-11e9-906c-b03d0b3016b8.png)

Then to resolve the broken dag, you just either:
- in the browser, go to `Admin -> Variables` and upload the variable config file: https://github.com/tuanavu/airflow-tutorial/blob/master/examples/intro-example/dags/config/example_variables.json
- or use the Airflow command line 

Both options should be covered in the tutorial. Let me know if you are still having issues.

**Comment by tsdeepak** [comment]
Thanks ..it worked

**Comment by ThomasBourgeois** [comment]
Thanks, perfectly worked !

**Comment by alanbantug** [comment]
Hi Tua, 

Good day.

I'm new to Airflow, and I have a little issue with the dags not appearing in the webserver. The logs are showing the message below:

There are 0 files in /usr/local/airflow/dags

Any ideas or suggestions? I found a lot of tips online, but none seems to be working. 

Thanks!

**Comment by mainakds3** [comment]
hi , 
**"docker-compose up**" failed while creating service webserver container. 
attached the error log.

Please help on this.
Thanks
[error-log.txt](https://github.com/tuanavu/airflow-tutorial/files/4751878/error-log.txt)

**Comment by prajwollamichhane11** [comment]
While running the docker-compose up, I am getting this error:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpfs_7l1zc'
[18819] Failed to execute script docker-compose
