### ISSUE TITLE
 'Variable example_variables_config does not exist'

### ISSUE THREAD

**Issue by ashattack** [tuanavu/airflow-tutorial#16]
Broken DAG: [/usr/local/airflow/dags/example_variables.py] 'Variable example_variables_config does not exist'

I am running Windows 10

I also check the container the file it there:
```
airflow@312a86dd0cfd:~$ cd dags
airflow@312a86dd0cfd:~/dags$ ls
config  example_twitter_dag.py  **example_variables.py**  __pycache__  tutorial.py
```

**Comment by tuanavu** [comment]
Hi @ashattack,

It is an Airflow variable that you need to import: https://github.com/tuanavu/airflow-tutorial/tree/master/examples/intro-example/dags/config

The guide to update the Airflow variable is included in the video tutorial. Please follow the tutorial here: https://www.applydatascience.com/airflow/airflow-variables/

This issue has been asked and resolved here if you want to take a look: https://github.com/tuanavu/airflow-tutorial/issues/14
