### ISSUE TITLE
Failed to execute script docker-compose

### ISSUE THREAD

**Issue by yunus89** [tuanavu/airflow-tutorial#17]
Executing `docker-compose up`  finished with an error after pulling postgres (postgres:9.6) successfully,

    $ docker-compose up
    Creating network "airflow-tutorial_default" with the default driver
    Pulling postgres (postgres:9.6)...
    9.6: Pulling from library/postgres
    f7e2b70d04ae: Pull complete
    027ad848ac9c: Pull complete
    7c040ef66643: Pull complete
    b891079ad2eb: Pull complete
    cb64a97e42d9: Pull complete
    1b88625f7d89: Pull complete
    a6ac0b663e77: Pull complete
    594497f0a694: Pull complete
    0189bc4eb328: Pull complete
    ded134b9085f: Pull complete
    5eb52aef3e1c: Pull complete
    54620ac345cf: Pull complete
    d7d7bc54ed9c: Pull complete
    cd9943f5a731: Pull complete
    Building webserver
    Traceback (most recent call last):
    File "docker-compose", line 6, in <module>
    File "compose\cli\main.py", line 71, in main
    File "compose\cli\main.py", line 127, in perform_command
    File "compose\cli\main.py", line 1080, in up
    File "compose\cli\main.py", line 1076, in up
    File "compose\project.py", line 475, in up
    File "compose\service.py", line 356, in ensure_image_exists
    File "compose\service.py", line 1080, in build
    File "site-packages\docker\api\build.py", line 142, in build
    TypeError: You must specify a directory to build in path
    [20384] Failed to execute script docker-compose

**Comment by tuanavu** [comment]
Hi @yunus89,

This looks like a docker error. Can you give me more info?

- Your docker, and docker-compose version you use? And the environment?

**Comment by yunus89** [comment]
Windows 10 Home, 64-bit OS.

Docker 

    $ docker version
    Client:
       Version:           18.09.0
       API version:       1.39
       Go version:        go1.11.1
       Git commit:        4d60db472b
       Built:             Thu Nov  8 21:14:51 2018
       OS/Arch:           windows/amd64
       Experimental:      false

     Server: Docker Engine - Community
       Engine:
         Version:          18.09.1
         API version:      1.39 (minimum version 1.12)
         Go version:       go1.10.6
         Git commit:       4c52b90
         Built:            Wed Jan  9 19:41:57 2019
         OS/Arch:          linux/amd64
         Experimental:     false

Docker Compose

     $ docker-compose version
     docker-compose version 1.23.1, build b02f1306
     docker-py version: 3.5.0
     CPython version: 3.6.6
     OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

**Comment by yunus89** [comment]
Hi @tuanavu ,

I just re-installed latest `Docker Tools` and everything works as expected
