### ISSUE TITLE
Airflow 1.10.2

### ISSUE THREAD

**Issue by yunus89** [tuanavu/airflow-tutorial#19]
How can i install airflow 1.10.2 with docker compose. When i change `docker-compose.yml` like so 

    ......
     webserver:
        image: puckel/docker-airflow:1.10.2
        build:
          context: https://github.com/puckel/docker-airflow.git#1.10.2
          dockerfile: Dockerfile
          args:
             AIRFLOW_DEPS: gcp_api,mysql        
        restart: always

     ......

Following error is thrown

    webserver_1  | [2019-04-08 08:07:09,123] {{settings.py:174}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=13
	webserver_1  | Traceback (most recent call last):
	webserver_1  |   File "/usr/local/bin/airflow", line 21, in <module>
	webserver_1  |     from airflow import configuration
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 36, in <module>
	webserver_1  |     from airflow import settings, configuration as conf
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 266, in <module>
	webserver_1  |     configure_orm()
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 188, in configure_orm
	webserver_1  |     engine = create_engine(SQL_ALCHEMY_CONN, **engine_args)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 431, in create_engine
	webserver_1  |     return strategy.create(*args, **kwargs)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
	webserver_1  |     dbapi = dialect_cls.dbapi(**dbapi_args)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 599, in dbapi
	webserver_1  |     import psycopg2
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
	webserver_1  |     from psycopg2._psycopg import (                     # noqa
	webserver_1  | ImportError: libpq.so.5: cannot open shared object file: No such file or directory
	webserver_1  | [2019-04-08 08:07:10,706] {{settings.py:174}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=1
	webserver_1  | [2019-04-08 08:07:10,711] {{settings.py:174}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=16
	webserver_1  | Traceback (most recent call last):
	webserver_1  |   File "/usr/local/bin/airflow", line 21, in <module>
	webserver_1  |     from airflow import configuration
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 36, in <module>
	webserver_1  |     from airflow import settings, configuration as conf
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 266, in <module>
	webserver_1  |     configure_orm()
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 188, in configure_orm
	webserver_1  |     engine = create_engine(SQL_ALCHEMY_CONN, **engine_args)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 431, in create_engine
	webserver_1  |     return strategy.create(*args, **kwargs)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
	webserver_1  |     dbapi = dialect_cls.dbapi(**dbapi_args)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 599, in dbapi
	webserver_1  |     import psycopg2
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
	webserver_1  |     from psycopg2._psycopg import (                     # noqa
	webserver_1  | ImportError: libpq.so.5: cannot open shared object file: No such file or directory
	webserver_1  | Traceback (most recent call last):
	webserver_1  |   File "/usr/local/bin/airflow", line 21, in <module>
	webserver_1  |     from airflow import configuration
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 36, in <module>
	webserver_1  |     from airflow import settings, configuration as conf
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 266, in <module>
	webserver_1  |     configure_orm()
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 188, in configure_orm
	webserver_1  |     engine = create_engine(SQL_ALCHEMY_CONN, **engine_args)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 431, in create_engine
	webserver_1  |     return strategy.create(*args, **kwargs)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
	webserver_1  |     dbapi = dialect_cls.dbapi(**dbapi_args)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 599, in dbapi
	webserver_1  |     import psycopg2
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
	webserver_1  |     from psycopg2._psycopg import (                     # noqa
	webserver_1  | ImportError: libpq.so.5: cannot open shared object file: No such file or directory
	postgres_1   | LOG:  incomplete startup packet
	webserver_1  | [2019-04-08 08:07:12,442] {{settings.py:174}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=7
	webserver_1  | Traceback (most recent call last):
	webserver_1  |   File "/usr/local/bin/airflow", line 21, in <module>
	webserver_1  |     from airflow import configuration
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 36, in <module>
	webserver_1  |     from airflow import settings, configuration as conf
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 266, in <module>
	webserver_1  |     configure_orm()
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 188, in configure_orm
	webserver_1  |     engine = create_engine(SQL_ALCHEMY_CONN, **engine_args)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 431, in create_engine
	webserver_1  |     return strategy.create(*args, **kwargs)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
	webserver_1  |     dbapi = dialect_cls.dbapi(**dbapi_args)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 599, in dbapi
	webserver_1  |     import psycopg2
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
	webserver_1  |     from psycopg2._psycopg import (                     # noqa
	webserver_1  | ImportError: libpq.so.5: cannot open shared object file: No such file or directory
	webserver_1  | [2019-04-08 08:07:14,131] {{settings.py:174}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=10
	webserver_1  | [2019-04-08 08:07:14,136] {{settings.py:174}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=1
	webserver_1  | Traceback (most recent call last):
	webserver_1  |   File "/usr/local/bin/airflow", line 21, in <module>
	webserver_1  |     from airflow import configuration
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 36, in <module>
	webserver_1  |     from airflow import settings, configuration as conf
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 266, in <module>
	webserver_1  |     configure_orm()
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 188, in configure_orm
	webserver_1  |     engine = create_engine(SQL_ALCHEMY_CONN, **engine_args)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 431, in create_engine
	webserver_1  |     return strategy.create(*args, **kwargs)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
	webserver_1  |     dbapi = dialect_cls.dbapi(**dbapi_args)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 599, in dbapi
	webserver_1  |     import psycopg2
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
	webserver_1  |     from psycopg2._psycopg import (                     # noqa
	webserver_1  | ImportError: libpq.so.5: cannot open shared object file: No such file or directory
	webserver_1  | Traceback (most recent call last):
	webserver_1  |   File "/usr/local/bin/airflow", line 21, in <module>
	webserver_1  |     from airflow import configuration
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 36, in <module>
	webserver_1  |     from airflow import settings, configuration as conf
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 266, in <module>
	webserver_1  |     configure_orm()
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 188, in configure_orm
	webserver_1  |     engine = create_engine(SQL_ALCHEMY_CONN, **engine_args)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 431, in create_engine
	webserver_1  |     return strategy.create(*args, **kwargs)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
	webserver_1  |     dbapi = dialect_cls.dbapi(**dbapi_args)
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 599, in dbapi
	webserver_1  |     import psycopg2
	webserver_1  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
	webserver_1  |     from psycopg2._psycopg import (                     # noqa
	webserver_1  | ImportError: libpq.so.5: cannot open shared object file: No such file or directory

**Comment by tuanavu** [comment]
Hi @yunus89,

After making the changes, you have to rebuild the image:
`docker-compose up -d --build`

**Comment by sud11** [comment]
Hi @tuanavu, I have the same issue when I have these files locally: Dockerfile, entrypoint.sh and airflow.cfg (all from here https://github.com/puckel/docker-airflow#1.10.2) and try to get the environment up using docker-compose up.

**Comment by tuanavu** [comment]
Hi @sud11,

I see. In this case, you are customizing your local Dockerfile, and all the config files. In this case, you have to change the `docker-compose.yml` file to build the Dockerfile locally, not the one from puckel github repo.

You may want to change your `docker-compose.yml` like this:

```
services:
    webserver:
        image: sud11/docker-airflow:1.10.2
        build: .        
```

This will ensure you build the local Dockerfile, then just build it using the command:

```
docker-compose up -d --build
```

**Comment by sud11** [comment]
This is my docker-compose.yml and I have the Dockerfile in the same dir.
`services:
    postgres:
        image: postgres:9.6
        container_name: airflow_db
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
            webserver:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: airflow_webserver
        depends_on:
            - postgres
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver`

I am not seeing the libpq.so.5 import error now.  😃 
Thanks @tuanavu 👍

**Comment by sud11** [comment]
This is my docker-compose.yml and I have the Dockerfile in the same dir.

<pre><code>services:
    postgres:
        image: postgres:9.6
        container_name: airflow_db
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: airflow_webserver
        depends_on:
            - postgres
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
</code></pre> 


I am not seeing the libpq.so.5 import error now. 😃
Thanks @tuanavu 👍

**Comment by tuanavu** [comment]
@sud11,

Great, glad you figure it out.
