### ISSUE TITLE
Issue on Install

### ISSUE THREAD

**Issue by rajaslm** [tuanavu/airflow-tutorial#20]
ERROR: for airflowtutorial_webserver_1  Cannot create container for service webs
erver: invalid volume specification: 'C:\Program Files\Docker Toolbox\airflow-tu
torial\examples\intro-example\dags:/usr/local/airflow/dags:rw'

**Comment by tuanavu** [comment]
Hi @rajaslm,

This looks like a path setting error between Linux and windows. Maybe you can try setting the environment variable:
`COMPOSE_CONVERT_WINDOWS_PATHS=1`

Example: https://stackoverflow.com/questions/41602083/docker-toolbox-windows-invalid-volume-specification
