### ISSUE TITLE
Persist airflow metadata

### ISSUE THREAD

**Issue by iamalonso** [tuanavu/airflow-tutorial#22]
Hi @tuanavu, I would like to persist the jobs metadata in airflow every time I turn off and lift the service via docker. It seems that every time I start the service a new database is created. Do you know how can I do that?

Regards ;)

**Comment by tuanavu** [comment]
Hi @iamalonso,

Airflow stores all metadata in the DB, in this case we use the Postgres DB docker service. In order to persist the metadata, you just need to create the database somewhere else, and change the config to point to your new database.

Hope it helps!
