### ISSUE TITLE
How scale Celery workers within docker-compose 

### ISSUE THREAD

**Issue by FSalazarH** [tuanavu/airflow-tutorial#24]
Hi, 

Using celeryExecutor, exist any way to scale the number of workers from docker-compose.yml file?

Thanks in advance.

**Comment by tuanavu** [comment]
Yes, you can always edit the `docker-compose.yml` using CeleryExecutor similar to this example:

- https://github.com/puckel/docker-airflow/blob/1.10.0-5/docker-compose-CeleryExecutor.yml

Then you can easily scale the number of workers using the parameter support

- https://github.com/puckel/docker-airflow#scale-the-number-of-workers
