### ISSUE TITLE
example_variables_config error

### ISSUE THREAD

**Issue by robertCadfarm** [tuanavu/airflow-tutorial#26]
Using the master branch, docker-compose up completes with error, and localhost:8080 comes
up with an error/warning:

Broken DAG: [/usr/local/airflow/dags/example_variables.py] 'Variable example_variables_config does not exist'

**Comment by robertCadfarm** [comment]
Duplicate issue.

**Comment by chandnidewani** [comment]
> Duplicate issue #14

Did this get solved? I'm facing the same issue.
