### ISSUE TITLE
how to add AWS credentials?

### ISSUE THREAD

**Issue by jinisaweaklearner** [tuanavu/airflow-tutorial#28]
Hi, 

It's really a nice tutorial! Thank you for sharing this.
I am using Lambda function in AWS with Airflow.

Just wonder how to add AWS credentials (e.g Secret and Access)?
```
[2020-04-13 03:13:40,720] {{models.py:1760}} ERROR - Unable to locate credentials
```

Many Thanks

Jin

**Comment by tuanavu** [comment]
Hi @jinisaweaklearner,

You can follow the instruction here: https://stackoverflow.com/questions/39997714/airflow-s3-connection-using-ui
