### ISSUE TITLE
Unable to run the webservice

### ISSUE THREAD

**Issue by vita-kulina** [tuanavu/airflow-tutorial#30]
Hi, thank you for sharing the tutorial.
After docker-compose up I'm getting the below error:

webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/models.py", line 377, in process_file
webserver_1  |     m = imp.load_source(mod_name, filepath)
webserver_1  |   File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
webserver_1  |     module = _load(spec)
webserver_1  |   File "<frozen importlib._bootstrap>", line 684, in _load
webserver_1  |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
webserver_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
webserver_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
webserver_1  |   File "/usr/local/airflow/dags/example_variables.py", line 33, in <module>
webserver_1  |     dag_config = Variable.get("example_variables_config", deserialize_json=True)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
webserver_1  |     return func(*args, **kwargs)
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/models.py", line 4551, in get
webserver_1  |     raise KeyError('Variable {} does not exist'.format(key))
webserver_1  | KeyError: 'Variable example_variables_config does not exist'

Can you advice what may be causing it?
Thanks

**Comment by JackTheSparrow** [comment]
Hi, I had the same error, but I found the solution that works for me at #14
