### ISSUE TITLE
Airflow Webserver fails to Start

### ISSUE THREAD

**Issue by EvanKaeding** [tuanavu/airflow-tutorial#34]
After running `docker-compose up`, all images install correctly but the web server never successfully launches. In the output, this appears to be the error:

`webserver_1  | KeyError: 'Variable example_variables_config does not exist'`

I'm unsure how to fix this.

**Comment by arturkuchynski** [comment]
@EvanKaeding https://github.com/tuanavu/airflow-tutorial/issues/14#issuecomment-467301310

**Comment by tuanavu** [comment]
Thanks for reporting this error, I have commented out the example_variables.py to avoid the missing variable error.
