### ISSUE TITLE
Broken DAG: [/usr/local/airflow/dags/example_variables.py] 'var1'

### ISSUE THREAD

**Issue by mikej345** [tuanavu/airflow-tutorial#37]
After adding the example_variables.py variable, I am getting a broken dag error 
Broken DAG: [/usr/local/airflow/dags/example_variables.py] 'var1'

**Comment by tuanavu** [comment]
Duplicate issue https://github.com/tuanavu/airflow-tutorial/issues/14

**Comment by tuanavu** [comment]
Thanks for reporting this error, I have commented out the example_variables.py to avoid the missing variable error.
