### ISSUE TITLE
Broken DAG: [/usr/local/airflow/dags/example_variables.py] 'Variable example_variables_config does not exist'

### ISSUE THREAD

**Issue by mickiizedx** [tuanavu/airflow-tutorial#43]
<img width="1438" alt="Screen Shot 2563-10-09 at 15 36 38" src="https://user-images.githubusercontent.com/59189106/95561661-41545880-0a45-11eb-9fcb-f716938ef08f.png">

How I can solve this problem ?

Broken DAG: [/usr/local/airflow/dags/example_variables.py] 'Variable example_variables_config does not exist'

**Comment by emdadulsadik** [comment]
+1 
<img width="1427" alt="Screenshot 2020-11-15 at 21 46 30" src="https://user-images.githubusercontent.com/14124209/99196345-1b307f80-278c-11eb-9908-e3bcbd5ca4c7.png">

**Comment by tuanavu** [comment]
Duplicate issue https://github.com/tuanavu/airflow-tutorial/issues/14
