### ISSUE TITLE
failed to solve with frontend dockerfile.v0: failed to read dockerfile

### ISSUE THREAD

**Issue by vjsreenivasan** [tuanavu/airflow-tutorial#46]
I get an error on `docker-compose up` while building the _webserver_

```
Status: Downloaded newer image for postgres:9.6
Building webserver
[+] Building 2.0s (1/1) FINISHED                                                
 => [internal] load git source https://github.com/puckel/docker-airflow.g  2.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount692468792/https:/github.com/puckel/docker-airflow.git#1.10.1/Dockerfile: no such file or directory                               
ERROR: Service 'webserver' failed to build
```   
I have shared the version of docker and docker-compose in the image attached.
any pointers to fix this issue...?

<img width="1482" alt="Screenshot 2021-03-16 at 7 57 51 PM" src="https://user-images.githubusercontent.com/50941626/111325935-28a23b80-8692-11eb-8f9e-0b40fd3aaae7.png">

**Comment by gntall** [comment]
I had the same exact issue, upgrading `docker-compose` to the latest version (1.28.6) worked for me!
