### ISSUE TITLE
Error executing docker-compose up -d

### ISSUE THREAD

**Issue by CarMoreno** [tuanavu/airflow-tutorial#48]
Hi, Thank you for the tutorial, I was watching the videos on your Youtube channel and you did an amazing job. I have a problem when I execute `docker-compose up -d`, the output is this:
```
Building webserver
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: /usr/lib/git-core/git-remote-https: /tmp/_MEImV8j6O/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /lib/x86_64-linux-gnu/libssh.so.4)
: exit status 128
ERROR: Service 'webserver' failed to build : Build failed
```
My environment is:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
Docker version 20.10.6, build 370c289
docker-compose version 1.29.1, build c34c88b2
```
I have the OPENSSL Library installed in my system:
```
> openssl version
OpenSSL 1.1.1f  31 Mar 2020
```
Could you help me, please?

**Comment by homedirectory** [comment]
had the same issue, the problem is that docker-compose 1.29.1 is built with openssl version 1.1.0
to fix this install docker-compose 1.28.0
